### ISSUE TITLE
The plugin for some reasons have a problem with locating the Prism launcher

### ISSUE THREAD

**Issue by CUR5EDFLVME** [Garulf/MC-Multi-Launcher#1]
[plugin.log](https://github.com/Garulf/MC-Multi-Launcher/files/10377338/plugin.log)
![image](https://user-images.githubusercontent.com/67831409/211420823-ba23b89d-e0af-4b30-b1af-54be3908398a.png)
![Discord_cECinN9Wlo](https://user-images.githubusercontent.com/67831409/211421234-e2a7033b-31c8-44c5-a964-c99ffd7c3ee2.gif)

Thank you for your help and the plugin!<3

**Comment by Garulf** [comment]
If you had your instance folder set to default the plugin was incorrectly looking for it in LOCAL directory and not in the ROAMING directory.

**Comment by Ravord** [comment]
I'm having a similar problem although here the two paths don't even match
![screen](https://user-images.githubusercontent.com/76743591/221234280-e22164b9-e257-4586-b515-169d3ce5fbfa.jpg)

**Comment by Garulf** [comment]
Looks liek its unable to locate the directory that contains your instances. The "MultiMC" folder should point to the directory that contains your launcher's exe file

**Comment by skotarek** [comment]
> Looks liek its unable to locate the directory that contains your instances. The "MultiMC" folder should point to the directory that contains your launcher's exe file

it does (let me repost the screen again, I wanted to create a new issue for this so I deleted the old comment, sorry)

![screen](https://user-images.githubusercontent.com/76743591/221237933-4e5d3c81-f69a-4c1c-b29e-8498ab46de46.jpg)

and here's how the folder looks like

![screen_2](https://user-images.githubusercontent.com/76743591/221238831-7d3efd26-4a42-49a8-958b-45ccf365b245.jpg)

**Comment by Garulf** [comment]
@Ravord Would you mind posting your multimc.cfg file? I'll take a look at what the issue is as soon as I can. Thanks!

**Comment by skotarek** [comment]
> @Ravord Would you mind posting your multimc.cfg file? I'll take a look at what the issue is as soon as I can. Thanks!

```
Analytics=false
AnalyticsClientID=00617119-9482-423f-9b31-31d02ffe22d7
AnalyticsSeen=2
ApplicationTheme=bright
AutoCloseConsole=true
AutoUpdate=true
CentralModsDir=mods
ConsoleFont=Courier
ConsoleFontSize=10
ConsoleMaxLines=100000
ConsoleOverflowStop=true
ConsoleWindowGeometry=AdnQywACAAAAAAG5AAAAnAAABcYAAAOiAAABwQAAALsAAAW+AAADmgAAAAAAAAAAB4A=
ConsoleWindowState=AAAA/wAAAAD9AAAAAAAAA/4AAALgAAAABAAAAAQAAAAIAAAACPwAAAAA
IconTheme=pe_colored
IconsDir=icons
InstSortMode=Name
InstanceDir=instances
JProfilerPath=
JVisualVMPath=
JavaArchitecture=64
JavaPath=C:/Program Files/Zulu/zulu-8-jre/bin/javaw.exe
JavaTimestamp=1674238330000
JavaVersion=1.8.0_362
JsonEditor=
JvmArgs=
Language=en_US
LastHostname=[hidden]
LastUsedGroupForNewInstance=
LaunchMaximized=false
MCEditPath=
MainWindowGeometry=AdnQywACAAAAAAG5AAAAqwAABcYAAAOxAAABwQAAAMoAAAW+AAADqQAAAAAAAAAAB4A=
MainWindowState=AAAA/wAAAAD9AAAAAAAAA4QAAAKEAAAABAAAAAQAAAAIAAAACPwAAAADAAAAAQAAAAEAAAAeAGkAbgBzAHQAYQBuAGMAZQBUAG8AbwBsAEIAYQByAwAAAAD/////AAAAAAAAAAAAAAACAAAAAQAAABYAbQBhAGkAbgBUAG8AbwBsAEIAYQByAQAAAAD/////AAAAAAAAAAAAAAADAAAAAQAAABYAbgBlAHcAcwBUAG8AbwBsAEIAYQByAQAAAAD/////AAAAAAAAAAA=
MaxMemAlloc=8192
MinMemAlloc=4096
MinecraftWinHeight=768
MinecraftWinWidth=1024
NewInstanceGeometry=AdnQywACAAAAAAG5AAAAnAAABcYAAAOiAAABwQAAALsAAAW+AAADmgAAAAAAAAAAB4A=
PagedGeometry=AdnQywACAAAAAAG5AAAAqwAABcYAAAOxAAABwQAAAMoAAAW+AAADqQAAAAAAAAAAB4A=
PasteEEAPIKey=multimc
PermGen=128
PostExitCommand=
PreLaunchCommand=
ProxyAddr=127.0.0.1
ProxyPass=
ProxyPort=8080
ProxyType=None
ProxyUser=
RecordGameTime=false
SelectedInstance=Beta 1.7.3
ShowConsole=false
ShowConsoleOnError=true
ShowGameTime=false
ShowGameTimeHours=false
ShowGlobalGameTime=false
ShownNotifications=
UpdateChannel=stable
UseNativeGLFW=true
UseNativeOpenAL=true
WrapperCommand=
```

**Comment by skotarek** [comment]
I just checked if a different launcher is working with this plugin and the answer is no, same exact problem also occurs with poly
