### ISSUE TITLE
GBK issues

### ISSUE THREAD

**Issue by huoyan1231** [Garulf/MC-Multi-Launcher#3]
![image](https://user-images.githubusercontent.com/53113734/218383320-b6f397d4-443c-4526-b6a8-78aecfc09563.png)

**Comment by Garulf** [comment]
Please see: https://github.com/Garulf/window-services/issues/11#issuecomment-1427408538

**Comment by huoyan1231** [comment]
> Please see: [Garulf/window-services#11 (comment)](https://github.com/Garulf/window-services/issues/11#issuecomment-1427408538)

not python issues
![image](https://user-images.githubusercontent.com/53113734/218386660-d1b6df6f-d855-4a90-9569-6efcac9156ba.png)

**Comment by Garulf** [comment]
Could you please link the log file for this plugin? Should be located in the plugins installed directory.

**Comment by huoyan1231** [comment]
[2023-02-13.txt](https://github.com/Garulf/MC-Multi-Launcher/files/10719326/2023-02-13.txt)


> Could you please link the log file for this plugin? Should be located in the plugins installed directory.

**Comment by huoyan1231** [comment]
[plugin.log](https://github.com/Garulf/MC-Multi-Launcher/files/10719341/plugin.log)
wrong log sry

> Could you please link the log file for this plugin? Should be located in the plugins installed directory.

**Comment by Garulf** [comment]
Please try this test version if you have the time:
[Minecraft Multi Launcher.zip](https://github.com/Garulf/MC-Multi-Launcher/files/10719455/Minecraft.Multi.Launcher.zip)

To have Flow Launcher install it for you type:
```
pm install https://github.com/Garulf/MC-Multi-Launcher/files/10719455/Minecraft.Multi.Launcher.zip
```

**Comment by huoyan1231** [comment]
> Please try this test version if you have the time: [Minecraft Multi Launcher.zip](https://github.com/Garulf/MC-Multi-Launcher/files/10719455/Minecraft.Multi.Launcher.zip)
> 
> To have Flow Launcher install it for you type:
> 
> ```
> pm install https://github.com/Garulf/MC-Multi-Launcher/files/10719455/Minecraft.Multi.Launcher.zip
> ```

![image](https://user-images.githubusercontent.com/53113734/218391542-b6e6de8a-ee1f-4e1a-97aa-fcc145fb4633.png)
it work good

**Comment by Garulf** [comment]
Great glad to hear!

It was a simple mistake I often make. Thanks for reporting this bug.
